### ISSUE TITLE
Behavior when selecting multiple taxonomy items

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-research-explorer#12]
From @kirstenkeister:

I had a query about the nature of the checkboxes when you have more than one item checked: is it purely additive, i.e it pulls any item that's in any of the taxonomies that are checked, or do we want it to only pull items that are in BOTH taxonomies. I guess this is also attached to what we were discussing regarding the item counts being updated when you check a single taxonomy.

See related: #3

**Comment by raffazizzi** [comment]
That could be useful. Not sure I'd expect that just by clicking the checkbox, but maybe with some more clever design...
