### ISSUE TITLE
Use another view to build <dl>'s in the left menu 

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-research-explorer#13]
Might be better to build the nested lists here 

https://github.com/umd-mith/mith-research-explorer/blob/master/src/js/views/categories-view.js#L30-L34

with another view with a tag element dl

**Comment by raffazizzi** [comment]
To clarify: there is no need of instantiating another view. Simply remove `<dl>` from the HTML structure and set CategoriesView's `tagName` to `"dl"`.
