### ISSUE TITLE
Pick a better variable name to avoid confusion

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-research-explorer#15]
"categoryName" might be clearer.

https://github.com/umd-mith/mith-research-explorer/blob/master/src/js/views/category-view.js#L32

**Comment by trevormunoz** [comment]
Also on https://github.com/umd-mith/mith-research-explorer/blob/master/src/js/views/category-view.js#L39 and https://github.com/umd-mith/mith-research-explorer/blob/master/src/js/views/category-view.js#L43

**Comment by kirstenkeister** [comment]
Keeping with the current naming scheme, maybe "catName"?
