### ISSUE TITLE
Project sort order is incorrect on initial load

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-research-explorer#2]
Might be a data issue?

**Comment by trevormunoz** [comment]
https://github.com/umd-mith/mith-research-explorer/blob/master/src/js/views/projects-view.js#L17

**Comment by raffazizzi** [comment]
I could not replicate this. @trevormunoz  could you try it on your machine and see what you get?

**Comment by trevormunoz** [comment]
@raffazizzi On first load, I get what appears to be the correct sort order (most recent first). (This is still not exactly what I expect. I would think projects that are still ongoing would be sorted to the top but that may be related to #17)

![screen shot 2015-12-01 at 3 18 32 pm](https://cloud.githubusercontent.com/assets/351120/11513006/fd39b096-983e-11e5-8c63-e88fac139ebd.png)

However, if I sort for oldest first and then sort back to most recent first, I get what appear to be undated projects first:
![screen shot 2015-12-01 at 3 19 08 pm](https://cloud.githubusercontent.com/assets/351120/11513025/1618f59a-983f-11e5-8c1c-d2789b1d59aa.png)

**Comment by trevormunoz** [comment]
Just confirming that issue with re-sorting back to most recent first is **not** resolved by #22

**Comment by raffazizzi** [comment]
Just fixed this is another round of corrections. I can either add to #22 or open another PR

**Comment by trevormunoz** [comment]
I think it would make sense in #22

**Comment by raffazizzi** [comment]
:+1:
